import img1 from "../assets/img1.png";
import img2 from "../assets/img2.png";

export const ITEM_CARD_DATA = [
  {
    image: img2,
    alt: "Auralite Graphite Over-Ear",
    category: "Headphones",
    title: "Auralite Graphite Over-Ear",
    price: "$149.00",
    subtitle: "Balanced sound profile with memory foam ear cushions and 30-hour battery life.",
    stockText: "In stock",
    rating: "★★★★★",
    note: "Quick view or add this item to the cart for fast checkout.",
  },
  {
    image: img1,
    alt: "Boreal Pulse Mini Speaker",
    category: "Speakers",
    title: "Boreal Pulse Mini Speaker",
    price: "$79.99",
    subtitle: "Ultra-portable speaker with waterproof design and clear midrange for outdoor use.",
    stockText: "Only 6 left",
    rating: "★★★★★",
    note: "Quick view or add this item to the cart for fast checkout.",
  },
  {
    image: img2,
    alt: "Crescendo IEM Pro",
    category: "Accessories",
    title: "Crescendo IEM Pro",
    price: "$229.00",
    subtitle: "Studio-grade in-ear monitors with detachable cable and tunable filters.",
    stockText: "Pre-order",
    rating: "★★★★☆",
    note: "Quick view or add this item to the cart for fast checkout.",
  },
  {
    image: img1,
    alt: "Auralite Graphite Over-Ear 2",
    category: "Headphones",
    title: "Auralite Graphite Over-Ear",
    price: "$159.00",
    subtitle: "Comfortable over-ear design with balanced bass and refined treble.",
    stockText: "In stock",
    rating: "★★★★★",
    note: "Quick view or add this item to the cart for fast checkout.",
  },
  {
    image: img2,
    alt: "Boreal Pulse Mini Speaker 2",
    category: "Speakers",
    title: "Boreal Pulse Mini Speaker",
    price: "$84.99",
    subtitle: "Compact wireless speaker with rich battery life and crisp sound.",
    stockText: "Low stock",
    rating: "★★★★☆",
    note: "Quick view or add this item to the cart for fast checkout.",
  },
  {
    image: img1,
    alt: "Crescendo IEM Pro 2",
    category: "Accessories",
    title: "Crescendo IEM Pro",
    price: "$199.00",
    subtitle: "Professional in-ear monitors tuned for clarity and deep bass response.",
    stockText: "In stock",
    rating: "★★★★★",
    note: "Quick view or add this item to the cart for fast checkout.",
  },
];
