export const ITEM_CARD_DATA = [
  {
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=300&fit=crop&crop=center",
    alt: "Auralite Graphite Over-Ear",
    category: "Headphones",
    title: "Auralite Graphite Over-Ear",
    price: "$149.00",
    subtitle: "Balanced sound profile with memory foam ear cushions and 30-hour battery life.",
    stockText: "In stock",
    rating: "★★★★★",
    note: "Quick view or add this item to the cart for fast checkout.",
  },
  {
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=300&fit=crop&crop=center",
    alt: "SonicWave Wireless Earbuds",
    category: "Speakers",
    title: "SonicWave Wireless Earbuds",
    price: "$129.99",
    subtitle: "True wireless earbuds with active noise cancellation and 8-hour battery life.",
    stockText: "Only 3 left",
    rating: "★★★★★",
    note: "Quick view or add this item to the cart for fast checkout.",
  },
  {
    image: "https://images.unsplash.com/photo-1484704849700-f032a568e944?w=400&h=300&fit=crop&crop=center",
    alt: "Crescendo IEM Pro",
    category: "Accessories",
    title: "Crescendo IEM Pro",
    price: "$229.00",
    subtitle: "Studio-grade in-ear monitors with detachable cable and tunable filters.",
    stockText: "Pre-order",
    rating: "★★★★☆",
    note: "Quick view or add this item to the cart for fast checkout.",
  },
  {
    image: "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=400&h=300&fit=crop&crop=center",
    alt: "Auralite Graphite Over-Ear 2",
    category: "Headphones",
    title: "Auralite Graphite Over-Ear",
    price: "$159.00",
    subtitle: "Comfortable over-ear design with balanced bass and refined treble.",
    stockText: "In stock",
    rating: "★★★★★",
    note: "Quick view or add this item to the cart for fast checkout.",
  },
  {
    image: "https://images.unsplash.com/photo-1545127398-14699f92334b?w=400&h=300&fit=crop&crop=center",
    alt: "Boreal Pulse Mini Speaker 2",
    category: "Speakers",
    title: "Boreal Pulse Mini Speaker",
    price: "$84.99",
    subtitle: "Compact wireless speaker with rich battery life and crisp sound.",
    stockText: "Low stock",
    rating: "★★★★☆",
    note: "Quick view or add this item to the cart for fast checkout.",
  },
  {
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=300&fit=crop&crop=center",
    alt: "Crescendo IEM Pro 2",
    category: "Accessories",
    title: "Crescendo IEM Pro",
    price: "$199.00",
    subtitle: "Professional in-ear monitors tuned for clarity and deep bass response.",
    stockText: "In stock",
    rating: "★★★★★",
    note: "Quick view or add this item to the cart for fast checkout.",
  },
];
